# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ dev, personnel_management, user_management, integration_test_user_management ]
  pull_request:
    branches: [ dev, personnel_management, user_management, integration_test_user_management ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "14.x"
    - name: install maildev
      run: npm install -g maildev
    - name: Run maildev
      run: maildev & sleep 10
    - name: Build with Gradle
      run: ./gradlew build
